export default [
  {
    login: "esin",
    id: 69767,
    node_id: "MDQ6VXNlcjY5NzY3",
    avatar_url: "https://avatars.githubusercontent.com/u/69767?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/esin",
    html_url: "https://github.com/esin",
    followers_url: "https://api.github.com/users/esin/followers",
    following_url: "https://api.github.com/users/esin/following{/other_user}",
    gists_url: "https://api.github.com/users/esin/gists{/gist_id}",
    starred_url: "https://api.github.com/users/esin/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/esin/subscriptions",
    organizations_url: "https://api.github.com/users/esin/orgs",
    repos_url: "https://api.github.com/users/esin/repos",
    events_url: "https://api.github.com/users/esin/events{/privacy}",
    received_events_url: "https://api.github.com/users/esin/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "xchanmolx",
    id: 16154263,
    node_id: "MDQ6VXNlcjE2MTU0MjYz",
    avatar_url: "https://avatars.githubusercontent.com/u/16154263?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/xchanmolx",
    html_url: "https://github.com/xchanmolx",
    followers_url: "https://api.github.com/users/xchanmolx/followers",
    following_url:
      "https://api.github.com/users/xchanmolx/following{/other_user}",
    gists_url: "https://api.github.com/users/xchanmolx/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/xchanmolx/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/xchanmolx/subscriptions",
    organizations_url: "https://api.github.com/users/xchanmolx/orgs",
    repos_url: "https://api.github.com/users/xchanmolx/repos",
    events_url: "https://api.github.com/users/xchanmolx/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/xchanmolx/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "mxmnk",
    id: 46030850,
    node_id: "MDQ6VXNlcjQ2MDMwODUw",
    avatar_url: "https://avatars.githubusercontent.com/u/46030850?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/mxmnk",
    html_url: "https://github.com/mxmnk",
    followers_url: "https://api.github.com/users/mxmnk/followers",
    following_url: "https://api.github.com/users/mxmnk/following{/other_user}",
    gists_url: "https://api.github.com/users/mxmnk/gists{/gist_id}",
    starred_url: "https://api.github.com/users/mxmnk/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/mxmnk/subscriptions",
    organizations_url: "https://api.github.com/users/mxmnk/orgs",
    repos_url: "https://api.github.com/users/mxmnk/repos",
    events_url: "https://api.github.com/users/mxmnk/events{/privacy}",
    received_events_url: "https://api.github.com/users/mxmnk/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "hacker8853",
    id: 76920935,
    node_id: "MDQ6VXNlcjc2OTIwOTM1",
    avatar_url: "https://avatars.githubusercontent.com/u/76920935?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/hacker8853",
    html_url: "https://github.com/hacker8853",
    followers_url: "https://api.github.com/users/hacker8853/followers",
    following_url:
      "https://api.github.com/users/hacker8853/following{/other_user}",
    gists_url: "https://api.github.com/users/hacker8853/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/hacker8853/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/hacker8853/subscriptions",
    organizations_url: "https://api.github.com/users/hacker8853/orgs",
    repos_url: "https://api.github.com/users/hacker8853/repos",
    events_url: "https://api.github.com/users/hacker8853/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/hacker8853/received_events",
    type: "User",
    site_admin: false,
  },
];
