export default {
  login: "waliaharsh74",
  id: 89077517,
  node_id: "MDQ6VXNlcjg5MDc3NTE3",
  avatar_url: "https://avatars.githubusercontent.com/u/89077517?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/waliaharsh74",
  html_url: "https://github.com/waliaharsh74",
  followers_url: "https://api.github.com/users/waliaharsh74/followers",
  following_url:
    "https://api.github.com/users/waliaharsh74/following{/other_user}",
  gists_url: "https://api.github.com/users/waliaharsh74/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/waliaharsh74/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/waliaharsh74/subscriptions",
  organizations_url: "https://api.github.com/users/waliaharsh74/orgs",
  repos_url: "https://api.github.com/users/waliaharsh74/repos",
  events_url: "https://api.github.com/users/waliaharsh74/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/waliaharsh74/received_events",
  type: "User",
  site_admin: false,
  name: "Harsh Walia",
  company:
    "Faculty Of Engineering & Technology, Gurukula Kangri Vishwavidyalaya",
  blog: "harshwalia.netlify.app",
  location: "India",
  email: null,
  hireable: null,
  bio: "Hey! welcome to my profile 😊\r\nI'm currently a Second-year B-Tech student of computer science,Web developer",
  twitter_username: null,
  public_repos: 14,
  public_gists: 0,
  followers: 4,
  following: 4,
  created_at: "2021-08-17T11:01:19Z",
  updated_at: "2022-09-20T18:48:06Z",
};
